apiVersion : apps/v1
kind: Deployment
metadata:
  name: "coolapi-deployment"
  namespace: coolapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "coolapi"
  template:
    metadata:
      labels:
        app: "coolapi"
    spec:
      containers:
        - name: "coolapi"
          image: "acryucongzhao2022.azurecr.io/coolapi:1.0.0"
          ports:
          - containerPort: 3000
          readinessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              cpu: "300m"
              memory: "64Mi"
            request:
              cpu: "600m"
              memory: "32Mi"
